apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magento-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/sajonaro/magento-plarform.git
    targetRevision: main
    path: cluster/overlays/default
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Uses default namespace in production cluster
  
  syncPolicy:
    # Manual sync for production - require explicit approval
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Ignore replica count changes made by HPA